### ISSUE TITLE
Google Colab can't run

### ISSUE THREAD

**Issue by gaoyunhe0108** [mattyamonaca/layerdivider#31]
!python demo.py share mistake

Downloading isnetis.onnx: 100% 176M/176M [00:01<00:00, 92.3MB/s]
Traceback (most recent call last):
  File "/content/layerdivider/demo.py", line 6, in <module>
    from ldivider.ld_processor import get_base, get_normal_layer, get_composite_layer
  File "/content/layerdivider/ldivider/ld_processor.py", line 10, in <module>
    from ldivider.bg_remover import get_foreground
  File "/content/layerdivider/ldivider/bg_remover.py", line 34, in <module>
    rmbg_model = rt.InferenceSession(model_path, providers=providers)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 408, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:124 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:117 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=0 ; hostname=45da94497a21 ; expr=cudaSetDevice(info_.device_id);

**Comment by mattyamonaca** [comment]
Please try using the GPU runtime.
