### ISSUE TITLE
Encounter error when run demo on the colab

### ISSUE THREAD

**Issue by universewill** [mattyamonaca/layerdivider#35]
I run the demo, and open the webui, then upload image and run, but got error below:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/layerdivider/demo.py", line 36, in divide_layer
    return self.segment_divide(input_image, loops, init_cluster, ciede_threshold, blur_size, layer_mode, h_split, v_split, n_cluster, alpha, th_rate, split_bg, area_th)
  File "/content/layerdivider/demo.py", line 46, in segment_divide
    masks = load_masks(output_dir)
  File "/content/layerdivider/ldivider/ld_utils.py", line 77, in load_masks
    with open(pkl_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/content/layerdivider/output/tmp/seg_layer/sorted_masks.pkl'
```

Where to find the sorted_masks.pkl?

**Comment by mousegame168** [comment]
the same issue.
