### ISSUE TITLE
google colab error 

### ISSUE THREAD

**Issue by xvlimit** [mattyamonaca/layerdivider#36]
Downloading isnetis.onnx: 100% 176M/176M [00:00<00:00, 206MB/s]
sam_vit_h_4b8939.pth: 100% 2.39G/2.39G [00:33<00:00, 77.3MiB/s]
Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://28091e69-5456-4d67.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/content/layerdivider/demo.py", line 36, in divide_layer
    return self.segment_divide(input_image, loops, init_cluster, ciede_threshold, blur_size, layer_mode, h_split, v_split, n_cluster, alpha, th_rate, split_bg, area_th)
  File "/content/layerdivider/demo.py", line 46, in segment_divide
    masks = load_masks(output_dir)
  File "/content/layerdivider/ldivider/ld_utils.py", line 77, in load_masks
    with open(pkl_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/content/layerdivider/output/tmp/seg_layer/sorted_masks.pkl'

Google Colabでスクリプトを実行しましたが、次のエラーが発生しました
SEGMENT または PSD を作成できないようです

**Comment by avi6111** [comment]
But While I press "Segment" Button, it has Error(but my be it's my env problems)
================================================== 
 File "E:\Program Files\AdobeProjectSrc\layerdivider\venv\lib\site-packages\gradio\utils.py", line 700, in wrapper
    response = f(*args, **kwargs)
  File "E:\Program Files\AdobeProjectSrc\layerdivider\demo.py", line 28, in segment_image
    mask_generator = get_mask_generator(pred_iou_thresh, stability_score_thresh, min_mask_region_area, model_dir, "demo")
  File "E:\Program Files\AdobeProjectSrc\layerdivider\ldivider\ld_segment.py", line 22, in get_mask_generator
    sam = sam_model_registry[model_type](checkpoint=sam_checkpoint)
  File "E:\Program Files\AdobeProjectSrc\layerdivider\venv\lib\site-packages\segment_anything\build_sam.py", line 15, in build_sam_vit_h
    return _build_sam(
  File "E:\Program Files\AdobeProjectSrc\layerdivider\venv\lib\site-packages\segment_anything\build_sam.py", line 105, in _build_sam
    state_dict = torch.load(f)
  File "E:\Program Files\AdobeProjectSrc\layerdivider\venv\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "E:\Program Files\AdobeProjectSrc\layerdivider\venv\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
