### ISSUE TITLE
When I run_gui into the local site and click on Create PSD, it shows the following error message

### ISSUE THREAD

**Issue by smallpostman10086** [mattyamonaca/layerdivider#41]
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Task exception was never retrieved
future: <Task finished name='zuvuz58rdno_1' coro=<Queue.process_events() done, defined at D:\layerdivider-main\venv\lib\site-packages\gradio\queueing.py:324> exception=AssertionError('No event data')>
Traceback (most recent call last):
  File "D:\layerdivider-main\venv\lib\site-packages\gradio\queueing.py", line 338, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "D:\layerdivider-main\venv\lib\site-packages\gradio\queueing.py", line 298, in call_prediction
    assert data is not None, "No event data"
AssertionError: No event data

**Comment by taidilixiang** [comment]
> This repo has soooooooooooooooo many environment problems. The owner of the repository is likely reusing the environment and therefore may not be aware of the issue.
> 
> I use anaconda on windows.
> 
> ## prepare
> Install CUDA(11.6) and CUDNN(8.x) from NVIDIA and do [#29 (comment)](https://github.com/mattyamonaca/layerdivider/issues/29#issuecomment-1653061845)
> 
> ## install packages.
> 1. `conda create -n 'layerdivider' python=3.10`
> 2. `conda activate layerdivider`
> 3. `python -m pip install -r requirements.txt`
> 4. `python -m pip install opencv-python pycocotools matplotlib onnxruntime onnx`  belong here:https://github.com/facebookresearch/segment-anything
> 5. `python -m pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118`
> 6. `python -m pip install cython packbits onnx onnxruntime-gpu opencv-python numpy Pillow scikit-learn psd-tools requests` # maybe already installed.
> 7. `python -m pip uninstall gradio` # Avoid gradio queue's bug.
> 8. `python -m pip install gradio==3.39.0`
> 9. `python -m pip uninstall pytoshop`
> 10. `python -m pip install pytoshop --no-cache-dir` # Avoid pytoshop's bug.
> 
> my pip freeze results
> I hope this helps someone.

Thank you for solving my problem
