### ISSUE TITLE
Local run_gui.ps1 OSError: [WinError 127]

### ISSUE THREAD

**Issue by ranran747** [mattyamonaca/layerdivider#45]
Traceback (most recent call last):
  File "C:\layerdivider\layerdivider\demo.py", line 8, in <module>
    from ldivider.ld_segment import get_mask_generator, get_masks, show_anns
  File "C:\layerdivider\layerdivider\ldivider\ld_segment.py", line 1, in <module>
    from segment_anything import sam_model_registry, SamAutomaticMaskGenerator, SamPredictor
  File "C:\layerdivider\layerdivider\venv\lib\site-packages\segment_anything\__init__.py", line 7, in <module>
    from .build_sam import (
  File "C:\layerdivider\layerdivider\venv\lib\site-packages\segment_anything\build_sam.py", line 7, in <module>
    import torch
  File "C:\layerdivider\layerdivider\venv\lib\site-packages\torch\__init__.py", line 122, in <module>
    raise err
OSError: [WinError 127] 指定されたプロシージャが見つかりません。 Error loading "C:\layerdivider\layerdivider\venv\lib\site-packages\torch\lib\cublas64_11.dll" or one of its dependencies.
続行するには、Enter キーを押してください...:

I've reinstalled it many times, but no improvement.

**Comment by muttondagger** [comment]
I have the exact same problem, I installed the CUDA and CUDNN and all the requirements and I still get that error

**Comment by muttondagger** [comment]
> I have the exact same problem, I installed the CUDA and CUDNN and all the requirements and I still get that error

My friend has found a fix for this, I have listed the steps in another page: https://github.com/mattyamonaca/layerdivider/issues/48
